In [1]:
import sys
print(sys.version)

3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]


In [2]:
print("Steve")

Steve


In [8]:
name = "Steve"
number = 99999999
print ("My name, {},{}! " .format(name,number))
print("My name is %s and number is %d" %(name,number))

My name, Steve,99999999! 
My name is Steve and number is 99999999


In [10]:
name = input("Enter your name: ")
match name:
    case "Steve":
        print("Name is Steve")
    case _:
        print("Invalid name")
        

Invalid name


In [16]:
statement = False
another_statement = False
if statement is True:
    print("Hai")
    # do something
    pass
elif another_statement is True: # else if
    print("another")
    # do something else
    
else:
    print("else")
    # do another thing
    

else


In [21]:
x = 4
if x == 2:
    print("x equals two!")
else:
    print("x does not equal to two.")

x does not equal to two.


In [26]:
x = [1,2,3]
y = [1,2,3]
print(x == y) # Prints out True
print(x is y) # Prints out False
print(x is x)

True
False
True


In [30]:
# change this code
number = 20
second_number = 0
first_array = [1,2,3]
second_array = [1,2]

if number > 15:
    print("1")

if first_array:
    print("2")

if len(second_array) == 2:
    print("3")

if len(first_array) + len(second_array) == 5:
    print("4")

if first_array and first_array[0] == 1:
    print("5")

if not second_number:
    print("6")

1
2
3
4
5
6


In [34]:
for i in range(0,10):
    for j in range (0,10):
        print(f"{i+1} * {j+1} = {(i+1)*(j+1)}")
    print("")   

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
1 * 10 = 10

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30

4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50

6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60

7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70

8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 10 = 80

9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90

10 * 1 = 10
10 

In [36]:
numbers = [
    951, 402, 984, 651, 360, 69, 408, 319, 601, 485, 980, 507, 725, 547, 544,
    615, 83, 165, 141, 501, 263, 617, 865, 575, 219, 390, 984, 592, 236, 105, 942, 941,
    386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345,
    399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217,
    815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,
    958, 609, 842, 451, 688, 753, 854, 685, 93, 857, 440, 380, 126, 721, 328, 753, 470,
    743, 527
]

# your code goes here
for number in numbers:
    if(number!=237):
        if(number%2==0):
            print(number)
    else:
        break

402
984
360
408
980
544
390
984
592
236
942
386
462
418
344
236
566
978
328
162
758
918


In [41]:
class MyClass:
    variable = "blah"

    def function(self):
        print("This is a message inside the class.")

myobjectx = MyClass()

print(myobjectx.function())

This is a message inside the class.
None


In [44]:
class MyClass:
    variable = "blah"

    def function(self):
        print("This is a message inside the class.")

myobjectx = MyClass()
myobjecty = MyClass()

myobjecty.variable = "yackity"

# Then print out both values
print(myobjectx.variable)
print(myobjecty.variable)

blah
yackity


In [53]:
class NumberHolder:
   def __init__(self, number):
       self.number = number

   def returnNumber(self):
       return self.number

print(NumberHolder(7).returnNumber()) #Prints '7'

7


In [63]:
class names:
    def __init__(self, a,b):
        self.a = a
        self.b = b
    def names(self):
        print(self.a+self.b)
class Student(names):
    pass
x =Student(5,7)
x.names()

12


In [74]:
name = "noel"
print(name[::-1])
number = 1234321
reversed_num = str(number)
reversed_num = int(reversed_num[::-1])
print(reversed_num)
if(number == reversed_num):
    print("Pallindrome")
else:
    print("Not pallindrome")

leon
1234321
Pallindrome


In [80]:
import math
from index import check 
n = 7
print(math.factorial(n))
print(check(n))

5040
Positive
None


In [82]:
class sample:
    def name(self,name):
        self.name = name
    def __add__(self,other):
        full_name = self.name+" "+other.name
        return full_name

first_name = sample()
second_name = sample()

first_name.name("Steve")
second_name.name("D James")

fullname = first_name+second_name
print(fullname)

Steve D James


In [83]:
list = [1,2,3,4,5,6,7,8,9,10]
print(list)
print(list[::-1])
list.append(15)
print(list)
list.insert(0,0)
print(list)
list.remove(5)
print(list)
list.pop(3)
print(list)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15]
[0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 15]
[0, 1, 2, 4, 6, 7, 8, 9, 10, 15]


In [3]:
tup1 = ('physics', 'chemistry', 1997, 2000)
tup2 = (1, 2, 3, 4, 5, 6, 7 )
print ("tup1[0]: ", tup1[0])
print ("tup2[1:5]: ", tup2[1:5])
tup1.count('physics')
tup1.index(1997)
tup1+tup2
tup1[-1]
tup1[::-1]


tup1[0]:  physics
tup2[1:5]:  (2, 3, 4, 5)


(2000, 1997, 'chemistry', 'physics')

In [21]:
thisdict = {
  "brand": "Ford",
  "electric": False,
  "year": 1964,
  "colors": ["red", "white", "blue"]
}   
print(len(thisdict))
print(type(thisdict))
print(thisdict.get("year"))
print(thisdict.get("colors"))
print(thisdict.keys())
print(thisdict.values())
print(thisdict.items())
print(thisdict["colors"][0])



4
<class 'dict'>
1964
['red', 'white', 'blue']
dict_keys(['brand', 'electric', 'year', 'colors'])
dict_values(['Ford', False, 1964, ['red', 'white', 'blue']])
dict_items([('brand', 'Ford'), ('electric', False), ('year', 1964), ('colors', ['red', 'white', 'blue'])])
red


In [6]:
dict = dict(name = "John", age = 36, country = "Norway")
print(dict)

{'name': 'John', 'age': 36, 'country': 'Norway'}


In [23]:
a = 1
b = 2
sum = lambda x,y : x + y
c = sum(a,b)
print(c)

2


In [32]:
l = [2,4,7,3,14,19]
for i in l:
   y = lambda x: (x%2)==1
   print(y(i))

False
False
True
True
False
True


In [42]:
a = set(["Jake", "John", "Eric"])
print(a)
b = set(["John", "Jill"])
print(b)
a.add("Noel")
print(a)
# a.pop()   
# print(a)
# a.pop()
# print(a)
print(a.intersection(b))
print(b.intersection(a))
print(a.symmetric_difference(b))
print(b.symmetric_difference(a))
print(a.difference(b))
print(b.difference(a))
print(a.union(b))


{'Eric', 'John', 'Jake'}
{'Jill', 'John'}
{'Noel', 'Eric', 'John', 'Jake'}
{'John'}
{'John'}
{'Eric', 'Jill', 'Noel', 'Jake'}
{'Noel', 'Eric', 'Jill', 'Jake'}
{'Noel', 'Eric', 'Jake'}
{'Jill'}
{'Noel', 'Eric', 'John', 'Jill', 'Jake'}


In [77]:
import re

txt = "The rain in Spain"
number = input("Enter your mobile number: ")
email = input("Enter your Email: ")
x = re.search("^The.*Spain$", txt)
x = re.search("Spain$", txt)
num = re.fullmatch("^[6-9]{1}[0-9]{9}$", number)
mail = re.match("^[A-Za-z0-9._]+@[A-Za-z0-9.-]+.[A-Z|a-z]{2,7}$", email)
print(x.span())
if(num):
    print("Valid Phone number")
else:
    print("Invalid")
if(mail):
    print("Valid email")
else:
    print("Invalid email")

(12, 17)
Invalid
Invalid email


In [72]:
def tri_recursion(k):
  if(k>0):
    result = k+tri_recursion(k-1)
    print(result)
  else:
    result = 0
  return result

print("\n\nRecursion Example Results")
tri_recursion(6)



Recursion Example Results
1
3
6
10
15
21


21

In [83]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
print(np_height)
np_weight = np.array(weight)
print(np_weight)


[1.87 1.87 1.82 1.91 1.9  1.85]
[81.65 97.52 95.25 92.98 86.18 88.45]


In [87]:
pip install bs4

Note: you may need to restart the kernel to use updated packages.
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     -------------------------------------- 129.4/129.4 kB 7.4 MB/s eta 0:00:00
  Running setup.py install for bs4: started
  Running setup.py install for bs4: finished with status 'done'


  DEPRECATION: bs4 is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import requests
URL = "https://www.geeksforgeeks.org/data-structures/"
r = requests.get(URL)
# print(r.content)

In [4]:

headers = {'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246"}
# Here the user agent is for Edge browser on windows 10. You can find your browser user agent from the above given link.
r = requests.get(url=URL, headers=headers)
# print(r.content)

In [6]:
import requests
from bs4 import BeautifulSoup
  
URL = "https://databeat.io"
r = requests.get(URL)
  
soup = BeautifulSoup(r.content, 'html5lib') # If this line causes an error, run 'pip install html5lib' or install html5lib
print(soup.prettify())

<!DOCTYPE html>
<html class="no-js ios" lang="en-US">
 <!-- head -->
 <head>
  <!--Google AdSense script-->
  <script async="" crossorigin="anonymous" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6817465509992148">
  </script>
  <!--Google AdSense script end-->
  <!-- meta -->
  <meta charset="utf-8"/>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
  <meta content="UcAEifpnkklf46hDbC9zO-j871SoOpmK9XJmP23PMUU" name="google-site-verification"/>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport"/>
  <meta content="We specialize in Data, Analytics, AdTech &amp; AdOperations" name="description"/>
  <meta content="Big Data, Data Science, Advanced Analytics, Yield, AdOperations, AdTech" name="keywords"/>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-118435531-1">
  </scrip

In [8]:
import requests
from bs4 import BeautifulSoup
import csv
   
URL = "http://www.values.com/inspirational-quotes"
r = requests.get(URL)
   
soup = BeautifulSoup(r.content, 'html5lib')
   
quotes=[]  # a list to store quotes
   
table = soup.find('div', attrs = {'id':'all_quotes'}) 
   
for row in table.findAll('div',
                         attrs = {'class':'col-6 col-lg-3 text-center margin-30px-bottom sm-margin-30px-top'}):
    quote = {}
    quote['theme'] = row.h5.text
    quote['url'] = row.a['href']
    quote['img'] = row.img['src']
    quote['lines'] = row.img['alt'].split(" #")[0]
    quote['author'] = row.img['alt'].split(" #")[1]
    quotes.append(quote)
print(quotes)

[]


In [13]:
import numpy as np
 
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("Array is of type: ", type(arr))
 
print("No. of dimensions: ", arr.ndim)
 
print("Shape of array: ", arr.shape)

print("Size of array: ", arr.size)
 
print("Array stores elements of type: ", arr.dtype)


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [27]:
a = np.array([1, 3, 5, 7], complex)  
print(a)
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [9, 10, 11, 23]])  
arr1 = np.array(['a'])  
print(arr)
print(arr1)
print(arr.ndim)
print(arr1.ndim)
print("Each item contains",arr.itemsize,"bytes")  
print("Each item contains",arr1.itemsize,"bytes")  
print("Each item is of the type",arr.dtype)  
print("Each item is of the type",arr1.dtype)  
print("Array Size:",arr.size)  
print("Array Size:",arr1.size)  
print("Shape:",arr.shape)  
print("Shape:",arr1.shape)  

[1.+0.j 3.+0.j 5.+0.j 7.+0.j]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 9 10 11 23]]
['a']
2
1
Each item contains 4 bytes
Each item contains 4 bytes
Each item is of the type int32
Each item is of the type <U1
Array Size: 12
Array Size: 1
Shape: (3, 4)
Shape: (1,)


In [3]:
# pandas function to read csv file
import pandas as pd
data = pd.read_excel("C:/Users/Steve D James/Downloads/AssignmentData.xlsx", sheet_name = "VisitData")
data.head()



VistID  Time_Spent  Internet_Usage    Ad_Topic Time_Period  Day  Month  \
0  1000187       78.01          227.72  product_12        Noon   30   July   
1  1000645       81.67          216.49   product_5     Morning    6  March   
2  1001347       69.74          227.53  product_27     Morning   20   June   
3  1002135       76.83          223.20  product_23        Noon   28   July   
4  1003369       41.73          162.05  product_13       Night   25   June   

   Year Clicked  
0  2020      No  
1  2020      No  
2  2020      No  
3  2020      No  
4  2020     Yes

In [11]:
data['Date'] = data['Day'].astype(str)+' '+data['Month'].str[0:3]+' '+data['Year'].astype(str)

In [10]:
data.drop('Date',axis = 1, inplace = True)

In [12]:
data.head()

VistID  Time_Spent  Internet_Usage    Ad_Topic Time_Period  Day  Month  \
0  1000187       78.01          227.72  product_12        Noon   30   July   
1  1000645       81.67          216.49   product_5     Morning    6  March   
2  1001347       69.74          227.53  product_27     Morning   20   June   
3  1002135       76.83          223.20  product_23        Noon   28   July   
4  1003369       41.73          162.05  product_13       Night   25   June   

   Year Clicked         Date  
0  2020      No  30 Jul 2020  
1  2020      No   6 Mar 2020  
2  2020      No  20 Jun 2020  
3  2020      No  28 Jul 2020  
4  2020     Yes  25 Jun 2020

In [13]:
# pandas dataframe
data.describe()

VistID   Time_Spent  Internet_Usage          Day    Year
count  2.000000e+03  2000.000000     2000.000000  2000.000000  2000.0
mean   2.398044e+06    67.085425      185.164220    16.249000  2020.0
std    7.850252e+05    15.524203       43.177338     8.956345     0.0
min    1.000187e+06    32.600000      104.780000     1.000000  2020.0
25%    1.729188e+06    55.740000      145.480000     8.000000  2020.0
50%    2.403496e+06    71.095000      193.445000    17.000000  2020.0
75%    3.067666e+06    79.822500      222.720000    24.000000  2020.0
max    3.742456e+06    91.430000      269.960000    31.000000  2020.0

In [22]:
import pyodbc 

conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=DESKTOP-1THVIIQ\MSSQLSERVER02;'
                      'Database=website_db;'
                      'Trusted_Connection=yes;')

cursor = conn.cursor()
cursor.execute('SELECT * FROM visitData')
# print(cursor)

for i in cursor:
    print(i)


(1000187.0, 78.01, 227.72, 'product_12', 'Noon', 30.0, 'July', 2020.0, 'No', '2020-07-30', '2020-08-09')
(1000645.0, 81.67, 216.49, 'product_5', 'Morning', 6.0, 'March', 2020.0, 'No', '2020-03-06', '2020-03-16')
(1001347.0, 69.74, 227.53, 'product_27', 'Morning', 20.0, 'June', 2020.0, 'No', '2020-06-20', '2020-06-30')
(1002135.0, 76.83, 223.2, 'product_23', 'Noon', 28.0, 'July', 2020.0, 'No', '2020-07-28', '2020-08-07')
(1003369.0, 41.73, 162.05, 'product_13', 'Night', 25.0, 'June', 2020.0, 'Yes', '2020-06-25', '2020-07-05')
(1003446.0, 83.16, 245.5, 'product_27', 'Noon', 28.0, 'July', 2020.0, 'No', '2020-07-28', '2020-08-07')
(1007369.0, 41.46, 159.77, 'product_24', 'Noon', 13.0, 'January', 2020.0, 'Yes', '2020-01-13', '2020-01-23')
(1008116.0, 67.91, 146.8, 'product_10', 'Mid-Night', 2.0, 'January', 2020.0, 'Yes', '2020-01-02', '2020-01-12')
(1008184.0, 40.17, 171.31, 'product_7', 'Noon', 5.0, 'February', 2020.0, 'Yes', '2020-02-05', '2020-02-15')
(1008446.0, 65.9, 232.68, 'product_3